#! /usr/bin/env sh

build() {
	BOOTSTRAP="$WORK/bootstrap"
	BOOTIMAGE="$WORK/bootimage"
	INITRAMFS="$WORK/initramfs"
	CRUXMEDIA="/root/cruxmedia"

	for dir in $BOOTSTRAP $BOOTIMAGE $INITRAMFS; do
		mkdir -p "$dir"
	done

	mkbootstrap "crux_gnulinux" "$BOOTSTRAP" --ports "$CRUXMEDIA/crux/core" $(cat packages.core)

	# mkbootstrap "crux_gnulinux" "$BOOTSTRAP" --ports "$CRUXMEDIA/kernel" "linux"

	install -d -m 0700 "$BOOTSTRAP/root/.ssh"

	if test -d "$HOME/.ssh"; then
		cd "$HOME/.ssh"
		for key in *".pub"; do
			cat "$key" >> "$BOOTSTRAP/root/.ssh/authorized_keys"
		done
		cd "$OLDPWD"
	fi

	sed -i "s/SERVICES=.*/SERVICES=(lo net crond sshd)/g" "$BOOTSTRAP/etc/rc.conf"

	mkinitramfs "$INITRAMFS" --output "$INITRAMFS.img"
	xz --check="crc32" --keep --threads=0 "$INITRAMFS.img"

	install -D "/boot/vmlinuz-"* "$BOOTIMAGE/boot/vmlinuz"
	install -D "$INITRAMFS.img.xz" "$BOOTIMAGE/boot/initrd"

	mkbootisofs "$BOOTIMAGE" \
		--legacy-boot "grub2" --efi "grub2" \
		--overlay "$BOOTSTRAP" --cpio \
		--output "$BOOT/crux-gnulinux-embedded-amd64.iso"
}
