#! /usr/bin/env sh

build() {
	mkbootstrap "crux_gnulinux" "$WORK" "/root/cruxmedia/crux/core/"*

	install -d -m 0700 "$WORK/root/.ssh"

	if cd "$HOME/.ssh"; then
		for key in *".pub"; do
			cat "$key" >> "$WORK/root/.ssh/authorized_keys"
		done
		cd "$OLDPWD"
	fi

	sed -i "s/SERVICES=.*/SERVICES=(lo net crond sshd)/g" "$WORK/etc/rc.conf"

	exportroot "$WORK" > "$PWD/rootfs.img"
}
